spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:spring-boot;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE
#  h2:
#    console:
#      enabled: true

logging:
  file: myapplication.log

info:
  app:
    version: @project.version@
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
