spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:spring-boot;Mode=Oracle;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /console/

security:
  basic:
    enabled: false